name: olive_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2 

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  http: ^1.0.0
  mobx: ^2.2.1 
  flutter_mobx: ^2.2.0 
  flutter_secure_storage: ^10.0.0-beta.4
  intl: any
  provider: ^6.1.5
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mobx_codegen: ^2.7.0 
  analyzer: ^6.11.0
  

flutter:
  uses-material-design: true
assets:
  - images/